initial commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -44,25 +44,37 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+      # - name: Terraform Init
+      #   run: terraform init
       - name: Terraform Init
-        run: terraform init
-
+        run: terraform -chdir=terraform/environments/${{ github.event.inputs.ENV }}/${{ github.event.inputs.RESOURCE }} init
+      
       - name: Terraform Validate
         run: terraform validate
 
       - name: Terraform Plan
-        id: tfplan
         run: |
-          VAR_FILE="terraform.tfvars"
-          if [ -f "$VAR_FILE" ]; then
-            echo "Using $VAR_FILE"
-          else
-            echo "ERROR: $VAR_FILE not found!"
-            exit 1
+          TF_DIR=terraform/environments/${{ github.event.inputs.ENV }}/${{ github.event.inputs.RESOURCE }}
+          VAR_FILE="$TF_DIR/terraform.tfvars"
+          if [ ! -f "$VAR_FILE" ]; then
+          echo "ERROR: $VAR_FILE not found!"
+          exit 1
           fi
-          terraform plan -var-file="$VAR_FILE" -out=tfplan.binary
-          terraform show -json tfplan.binary > plan.json
-          echo "plan_created=true" >> $GITHUB_OUTPUT
+          terraform -chdir="$TF_DIR" plan -var-file="$VAR_FILE" -out=tfplan.binary
+
+      # - name: Terraform Plan
+      #   id: tfplan
+      #   run: |
+      #     VAR_FILE="terraform.tfvars"
+      #     if [ -f "$VAR_FILE" ]; then
+      #       echo "Using $VAR_FILE"
+      #     else
+      #       echo "ERROR: $VAR_FILE not found!"
+      #       exit 1
+      #     fi
+      #     terraform plan -var-file="$VAR_FILE" -out=tfplan.binary
+      #     terraform show -json tfplan.binary > plan.json
+      #     echo "plan_created=true" >> $GITHUB_OUTPUT
 
       - name: Upload Terraform Plan Files
         uses: actions/upload-artifact@v4
